config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


root 'welcome#index'
get 'welcome/index'
get 'my_portfolio',to: 'users#my_portfolio'
get 'search_stock', to: 'stocks#search'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      secret_token: 'secret_token',
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
          new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end     
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        render 'users/my_portfolio'
      else 
        flash[:alert] = "ТАКОГО ТИКЕРА НЕ СУЩЕСТВУЕТ"
        redirect_to my_portfolio_path
      end
    else 
      flash[:alert] = "Введите символ тикера !!!!!!!!!!!!!!!!!!!!!"
      redirect_to my_portfolio_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index

	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinancialTrack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <%= link_to 'Click to see stock price', my_portfolio_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </div>  
  </nav>
  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
    </body>
</html>

app/views/stocks/search.html.erb
<h1>Stocks#search</h1>
<p>Find me in app/views/stocks/search.html.erb</p>

app/views/users/_result.html.erb
<% if @stock %>
<div class="card card-header col-9">
  <strong> Symbol</strong> <%= @stock.ticker %>
  <strong> Company name</strong> <%= @stock.name %>
  <strong> Price</strong> <%= @stock.last_price %>
  
</div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My_portfolio</h1>

<div class='search-area'>  
  <h2><p>Search stocks</p></h2>
    <%= form_tag search_stock_path, method: :get do %>
      <div class='form-group row'>

        <div class='col-sm-9 small-right-padding'>
          <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: 'form-control form-control-lg' %>
        </div>
        <div class='col-sm-3 small-left-padding'>
          <%= button_tag type: :submit, class: "btn btn-danger" do %>
            <%= fa_icon 'search 2x' %>    
          <% end %>
        </div>
      </div>

    <% end %>
    
</div>
<div class="container col-sm-6">
  <%= render 'users/result' %>
</div>

app/views/welcome/index.html.erb
<h1>Добро пожаловать в фнаносвый трекер</h1>

<%= link_to 'Singout', destroy_user_session_path, method: :delete %>